src/App/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use DateTime;
use App\Model\ListableDatasInterface;
use URLify;


/**
 * @ORM\Entity(repositoryClass="App\Entity\NewsRepository")
 * @ORM\Table(name="news")
 * @ORM\HasLifecycleCallbacks
 */
class News implements ListableDatasInterface
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var string $title
	 *
	 * @ORM\Column(type="string", length=250)
	 */
	private $title;

	/**
	 * @var string $uri
	 *
	 * @ORM\Column(type="string", length=250)
	 */
	private $uri;

	/**
	 * @var string $description
	 *
	 * @ORM\Column(type="text")
	 */
	private $description;

	/**
	 * @var string $content
	 *
	 * @ORM\Column(type="text")
	 */
	private $content;

	/**
	 * @var DateTime $createdAt
	 *
	 * @ORM\Column(type="datetime")
	 */
	private $createdAt;

	/**
	 * Get id
	 * 
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}
	
	/**
	 * Set id
	 *
	 * @param integer $id
	 * @return News
	 */
	public function setId($id)
	{
		$this->id = $id;
	
		return $this;
	}

	/**
	 * Get title
	 * 
	 * @return string
	 */
	public function getTitle()
	{
		return $this->title;
	}
	
	/**
	 * Set title
	 *
	 * @param string $title
	 * @return News
	 */
	public function setTitle($title)
	{
		$this->title = $title;
	
		return $this;
	}

	/**
	 * Get description
	 * 
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}
	
	/**
	 * Set description
	 *
	 * @param string $description
	 * @return News
	 */
	public function setDescription($description)
	{
		$this->description = $description;
	
		return $this;
	}

	/**
	 * Get uri
	 * 
	 * @return string
	 */
	public function getUri()
	{
		return $this->uri;
	}
	
	/**
	 * Set uri
	 *
	 * @param string $uri
	 * @return News
	 */
	public function setUri($uri)
	{
		$this->uri = $uri;
	
		return $this;
	}

	/**
	 * Get content
	 * 
	 * @return string
	 */
	public function getContent()
	{
		return $this->content;
	}
	
	/**
	 * Set content
	 *
	 * @param string $content
	 * @return News
	 */
	public function setContent($content)
	{
		$this->content = $content;
	
		return $this;
	}

	/**
	 * Get createdAt
	 * 
	 * @return string
	 */
	public function getCreatedAt()
	{
		return $this->createdAt->format('d/m/Y à H:i');
	}
	
	/**
	 * Set createdAt
	 *
	 * @param DateTime $createdAt
	 * @return News
	 */
	public function setCreatedAt(DateTime $createdAt)
	{
		$this->createdAt = $createdAt;
	
		return $this;
	}

	/**
	 * @ORM\PrePersist
	 */
	public function prePersit()
	{
		$this->createdAt = new DateTime('now');
		$this->uri = URLify::filter($this->getTitle());
	}

	public function getListFields()
	{
		return array(
			'Titre de l\'actualité' => $this->getTitle(),
			'Créé le' => $this->getCreatedAt()
		);
	}

    public function getShowRole()
    {
        return 'ROLE_ADMIN';
    }

    public function getEditRole()
    {
        return 'ROLE_ADMIN';
    }

    public function getDeleteRole()
    {
        return 'ROLE_ADMIN';
    }

    public function getCreateRole()
    {
        return 'ROLE_ADMIN';
    }

	/**
	 * String representation
	 * 
	 * @return string
	 */
	public function __toString()
	{
		return $this->getTitle();
	}

	/**
	 * default contructor
	 */
	public function __construct()
	{
		$this->createdAt = new DateTime();
	}
}

src/App/Resources/views/Helper/datatable.html.twig
<h2>{{title}}</h2>
<hr/>

{% if permissions is empty or permissions.create %}
<p>
	<a href="{{ path(routes.create) }}" class="btn btn-primary">Rajouter</a>
</p>
{% endif %}

{% if heads %}

    {{knp_pagination_render(datas)}}

	<table class="table table-hover table-bordered">

		<thead>
			<tr>
			{% for head in heads %}
				<th>{{head}}</th>
			{% endfor %}
				<th>Actions</th>
			</tr>
		</thead>	

		<tbody>
			{% for data in datas %}
				<tr>
					{% for value in data.listFields %}
						<td>{{value}}</td>
					{% endfor %}
						<td>
                            {% if permissions.edit %}
							    <a href="{{ path(routes.edit, {'id' : data.id}) }}" class="btn btn-mini">éditer</a>
                            {% endif %}

                            {% if permissions.delete %}
                                <form method="POST" action="{{ path(routes.delete, {'id' : data.id}) }}" 
                                    onsubmit="return confirm('Êtes vous sur ?')">
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <input type="submit" class="btn btn-mini btn-danger" value="supprimer" />
                                </form>
                            {% endif %}
						</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
    {{knp_pagination_render(datas)}}
{% else %}
	<div class="alert alert-info">
		<h1>Aucune données pour le moment :(</h1>
		<p>
			Apparement vous n'avez pas encore créé de données. Peut-être devriez vous commencer
			par cliqué sur le bouton "Rajouter" pour créé une nouvelle entrée.
		</p>
	</div>
{% endif %}